# Generated by Django 5.0.6 on 2024-05-24 07:19

import storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('attachment', models.FileField(storage=storage.HadoopStorage(), upload_to='')),
            ],
        ),
    ]
